### ISSUE TITLE
Random Events system

### ISSUE THREAD

**Issue by LiamOxley** [RobinStephenson/jbt-2#22]
## Description
Implement a system that generates a random event during the production phase, that affects the map in a distinct way and will inform the player of the event details.

Also generate a selection of these random events.

### Client Requirements
2.5

### Developer Requirements
NA

## Estimated completion time
This issue should be completed in:
2 days.

**Comment by RobinStephenson** [comment]
related #33

**Comment by RobinStephenson** [comment]
branch: random-events

**Comment by RobinStephenson** [comment]
This issue will take a little longer as i've come into some problems working out how to nicely load RandomEvents from file. However, Ive now found a good way to do it using Json rather than XML. Then I can use UnityEngine.JsonUtility.FromJson to create some configuration objects to get the data.

Whats done:
The events system is called by the game manager,
It randomly triggers events, how often and how many can be configured.
Tiles take into account random events when calculating production.

What needs doing:
Load events from file.
Create visual indication of events on map, and a message explaining the event.
Testing.

**Comment by Mikeywalsh** [comment]
I think it would be best to load the JSON file into a static array/dictionary when the game is first ran.
If you want to use a JSON parser, i've used:

http://wiki.unity3d.com/index.php/SimpleJSON

in the past. It's an extremely lightweight parser which doesn't contain things we won't use like attributes and such. But whatever works best for you is fine!

**Comment by RobinStephenson** [comment]
Yeah that looks like what I wanted to use but couldnt find!

**Comment by RobinStephenson** [comment]
Will make my life a lot easier
