### ISSUE TITLE
Improve market transaction failures

### ISSUE THREAD

**Issue by LiamOxley** [RobinStephenson/jbt-2#36]
Not able to buy or sell resources in the market.
Unclear when you can use the market.
Not sure if supply-and-demand feature is implemented.

**Comment by RobinStephenson** [comment]
Going to look at the code and put a summary of the problem(s) on here so we can agree on a time estimate.

**Comment by RobinStephenson** [comment]
The issue was that the market did not have any ore to sell and was thus declining the transaction. We should instead make this error more clear to the user as all that happens is the buy cost flashes red for a second.

**Comment by RobinStephenson** [comment]
To fix we should make the market through a more descriptive exception. We should also make the marketScript.PlayPurchaseDeclinedAnimation give the user more information eg which resource the market does not have enough money to purchase of.
Alternatively we should change the UI and rather than having text inputs for the numbers we should have buttons + and - buttons and disable + when the max quantity is reached and disable - on zero

**Comment by Mikeywalsh** [comment]
Don't think we are going to have enough time to do this. It isn't as bas as it was, now that the user is made aware of how much money the market has, but with all the other issues going on, i'm not sure this has enough priority to be finished.
